### ISSUE TITLE
Not working with 1.999

### ISSUE THREAD

**Issue by ElHyperion** [Garbius/WootingPlugin#2]
Crashes the game few seconds after the splash logo shows up.
log: https://hastebin.com/egigilokez.apache

**Comment by Garbius** [comment]
My apologies for the late response. I haven't been playing in a while. A new version is in development that is based on Harmony. It will hopefully be a bit more robust to new updates. It will be released soon™ (likely in the coming days).

**Comment by Garbius** [comment]
The latest release **Works on my machine™**. Try it out and report back with the results.

**Comment by ElHyperion** [comment]
My apologies for another late response. Keeps crashing a few seconds upon the initial splash screen (1.201).
Looks like this exception could be interesting to you:
![image](https://user-images.githubusercontent.com/5313557/204098784-998623aa-aad7-4f1c-8e4f-24e3b06664d2.png)

EDIT: Issue got resolved upon unblocking the .dll files by going into properties and hitting the unlock checkbox, perhaps you could add it into the description?

Much thanks for this plugin, now Space Engineers works with Wooting just as I imagined it would! I can finally disable gamepad mapping override so that I can use analog input as well as being able type "WASD" keys into the menus without having to switch the profile, and the Xbox keys overlay is gone as well!

Btw, just found out that it works even with a typing profile, does this mean that I cannot adjust the joystick curves in wootility and have the changes reflected in the game? I find it too difficult to hit the "walking" pace whereas running can have a much narrower range, as you can simply floor the key to run.
